version: '3'

services:
  specmatic:
    image: znsio/specmatic:latest
    command: stub --examples /usr/src/app/examples
    volumes:
      - ./specmatic.yaml:/usr/src/app/specmatic.yaml
      - ./examples:/usr/src/app/examples
    ports:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8621:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - specmatic