version: '3'

services:
  specmatic:
    image: znsio/specmatic:2.0.8
    command: stub
    volumes:
      - ./specmatic.yaml:/usr/src/app/specmatic.yaml
    ports:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8621:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - specmatic