version: '3.8'

services:
  ctk:
    image: znsio/specmatic:latest
    environment:
      MAX_TEST_REQUEST_COMBINATIONS: 5
      EXTENSIBLE_SCHEMA: 'true'
    volumes:
      - './SEND_ME:/usr/src/app/build/reports/specmatic/html:rw'
      - './specmatic.yaml:/usr/src/app/specmatic.yaml'
      - './examples:/usr/src/app/examples'
      - './TroubleTicket-updated.yaml:/usr/src/app/TroubleTicket-updated.yaml'
    command: >
      test
      --examples '/usr/src/app/examples'
      --filter-not-name 'TroubleTicket_create_example, -> 202, -> 50,-> 401,-> 403,-> 405'
      --filter-name 'DELETE /troubleTicket/(id:string),GET /troubleTicket ->,GET /troubleTicket/(id:string),POST /troubleTicket ->'
      --testBaseURL='http://host.docker.internal:8621/tmf-api/troubleTicket/v5'
