openapi: 3.0.1
info:
  title: Random
  version: "1"
paths:
  /random:
    post:
      summary: With examples
      requestBody:
        content:
          application/json:
            schema:
              required:
              - id
              properties:
                id:
                  type: number
      responses:
        "200":
          description: Random
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing the bad request
                  details:
                    type: string